secret:
  username: "cG9zdGdyZXM="   # base64-кодированное "postgres"
  password: "cGFzc3dvcmQ="   # base64-кодированное "password"

config:
  database_url: "jdbc:postgresql://188.242.76.99:5432/job4j_devops?sslmode=disable"

containers:
  image: "delinrus/job4j_devops:v.1.0.7"



