apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 8080
